$store = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore'; $appx = Get-AppxPackage -Name Microsoft.SecHealthUI; $sids = @('S-1-5-18'); $sids += Get-ChildItem $store -ea 0 | % { $_.PSChildName } | ? { $_.StartsWith('S-1-5-21') }; New-Item -Path "$store\Deprovisioned\$($appx.PackageFamilyName)" -ItemType RegistryKey -Force | Out-Null; foreach ($sid in $sids) { New-Item -Path "$store\EndOfLife\$sid\$($appx.PackageFullName)" -ItemType RegistryKey -Force | Out-Null }; $appx | Remove-AppxPackage
irm raw.githubusercontent.com/ionuttbara/windows-defender-remover/main/Remove_Defender/RemoveDefender.reg -OutFile $env:TEMP\RemoveDefender.reg;irm raw.githubusercontent.com/ionuttbara/windows-defender-remover/main/Remove_SecurityComp/Remove_SecurityComp.reg -OutFile $env:TEMP\Remove_SecurityComp.reg

Remove-Item -Force "C:\Windows\WinSxS\FileMaps\wow64_windows-defender*.manifest"
Remove-Item -Force "C:\Windows\WinSxS\FileMaps\x86_windows-defender*.manifest"
Remove-Item -Force "C:\Windows\WinSxS\FileMaps\amd64_windows-defender*.manifest"
Remove-Item -Force "C:\Windows\System32\SecurityAndMaintenance_Error.png"
Remove-Item -Force "C:\Windows\System32\SecurityAndMaintenance.png"
Remove-Item -Force "C:\Windows\System32\SecurityHealthSystray.exe"
Remove-Item -Force "C:\Windows\System32\SecurityHealthService.exe"
Remove-Item -Force "C:\Windows\System32\SecurityHealthHost.exe"
Remove-Item -Force "C:\Windows\System32\drivers\SgrmAgent.sys"
Remove-Item -Force "C:\Windows\System32\drivers\WdDevFlt.sys"
Remove-Item -Force "C:\Windows\System32\drivers\WdBoot.sys"
Remove-Item -Force "C:\Windows\System32\drivers\WdFilter.sys"
Remove-Item -Force "C:\Windows\System32\wscsvc.dll"
Remove-Item -Force "C:\Windows\System32\drivers\WdNisDrv.sys"
Remove-Item -Force "C:\Windows\System32\wscproxystub.dll"
Remove-Item -Force "C:\Windows\System32\wscisvif.dll"
Remove-Item -Force "C:\Windows\System32\SecurityHealthProxyStub.dll"
Remove-Item -Force "C:\Windows\System32\smartscreen.dll"
Remove-Item -Force "C:\Windows\SysWOW64\smartscreen.dll"
Remove-Item -Force "C:\Windows\System32\smartscreen.exe"
Remove-Item -Force "C:\Windows\SysWOW64\smartscreen.exe"
Remove-Item -Force "C:\Windows\System32\DWWIN.EXE"
Remove-Item -Force "C:\Windows\SysWOW64\smartscreenps.dll"
Remove-Item -Force "C:\Windows\System32\smartscreenps.dll"
Remove-Item -Force "C:\Windows\System32\SecurityHealthCore.dll"
Remove-Item -Force "C:\Windows\System32\SecurityHealthSsoUdk.dll"
Remove-Item -Force "C:\Windows\System32\SecurityHealthUdk.dll"
Remove-Item -Force "C:\Windows\System32\SecurityHealthAgent.dll"
Remove-Item -Force "C:\Windows\System32\wscapi.dll"
Remove-Item -Force "C:\Windows\System32\wscadminui.exe"
Remove-Item -Force "C:\Windows\SysWOW64\GameBarPresenceWriter.exe"
Remove-Item -Force "C:\Windows\System32\GameBarPresenceWriter.exe"
Remove-Item -Force "C:\Windows\SysWOW64\DeviceCensus.exe"
Remove-Item -Force "C:\Windows\SysWOW64\CompatTelRunner.exe"
Remove-Item -Force "C:\Windows\system32\drivers\msseccore.sys"
Remove-Item -Force "C:\Windows\system32\drivers\MsSecFltWfp.sys"
Remove-Item -Force "C:\Windows\system32\drivers\MsSecFlt.sys"
Remove-Item -Recurse -Force "C:\Windows\WinSxS\amd64_security-octagon*"
Remove-Item -Recurse -Force "C:\Windows\WinSxS\x86_windows-defender*"
Remove-Item -Recurse -Force "C:\Windows\WinSxS\wow64_windows-defender*"
Remove-Item -Recurse -Force "C:\Windows\WinSxS\amd64_windows-defender*"
Remove-Item -Recurse -Force "C:\Windows\SystemApps\Microsoft.Windows.AppRep.ChxApp_cw5n1h2txyewy"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows Defender"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection"
Remove-Item -Recurse -Force "C:\Program Files (x86)\Windows Defender Advanced Threat Protection"
Remove-Item -Recurse -Force "C:\Program Files\Windows Defender Advanced Threat Protection"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows Security Health"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Storage Health"
Remove-Item -Recurse -Force "C:\WINDOWS\System32\drivers\wd"
Remove-Item -Recurse -Force "C:\Program Files (x86)\Windows Defender"
Remove-Item -Recurse -Force "C:\Program Files\Windows Defender"
Remove-Item -Recurse -Force "C:\Windows\System32\SecurityHealth"
Remove-Item -Recurse -Force "C:\Windows\System32\WebThreatDefSvc"
Remove-Item -Recurse -Force "C:\Windows\System32\Sgrm"
Remove-Item -Recurse -Force "C:\Windows\Containers\WindowsDefenderApplicationGuard.wim"
Remove-Item -Recurse -Force "C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\DefenderPerformance"
Remove-Item -Recurse -Force "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DefenderPerformance"
Remove-Item -Recurse -Force "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Defender"
Remove-Item -Recurse -Force "C:\Windows\System32\Tasks_Migrated\Microsoft\Windows\Windows Defender"
Remove-Item -Recurse -Force "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender"
Remove-Item -Recurse -Force "C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\Defender"
Remove-Item -Recurse -Force "C:\Windows\System32\HealthAttestationClient"
Remove-Item -Recurse -Force "C:\Windows\GameBarPresenceWriter"
Remove-Item -Recurse -Force "C:\Windows\bcastdvr"
Remove-Item -Recurse -Force "C:\Windows\Containers\serviced\WindowsDefenderApplicationGuard.wim"
