Set-Service -Name "ALG" -StartupType "Manual" *> $null
Set-Service -Name "AppIDSvc" -StartupType "Manual" *> $nulle
Set-Service -Name "AppMgmt" -StartupType "Manual" *> $null
Set-Service -Name "AppReadiness" -StartupType "Manual" *> $null
Set-Service -Name "AppVClient" -StartupType "Disabled" *> $null
Set-Service -Name "AppXSvc" -StartupType "Manual" *> $null
Set-Service -Name "Appinfo" -StartupType "Manual" *> $null
Set-Service -Name "AssignedAccessManagerSvc" -StartupType "Disabled" *> $null
Set-Service -Name "AudioEndpointBuilder" -StartupType "Automatic" *> $null
Set-Service -Name "AudioSrv" -StartupType "Automatic" *> $null
Set-Service -Name "Audiosrv" -StartupType "Automatic" *> $null
Set-Service -Name "AxInstSV" -StartupType "Manual" *> $null
Set-Service -Name "BDESVC" -StartupType "Manual" *> $null
Set-Service -Name "BFE" -StartupType "Automatic" *> $null
Set-Service -Name "BITS" -StartupType "AutomaticDelayedStart" *> $null
Set-Service -Name "BTAGService" -StartupType "Manual" *> $null
Set-Service -Name "BcastDVRUserService_*" -StartupType "Manual" *> $null
Set-Service -Name "BluetoothUserService_*" -StartupType "Manual" *> $null
Set-Service -Name "BrokerInfrastructure" -StartupType "Automatic" *> $null
Set-Service -Name "Browser" -StartupType "Manual" *> $null
Set-Service -Name "BthAvctpSvc" -StartupType "Automatic" *> $null
Set-Service -Name "CDPSvc" -StartupType "Manual" *> $null
Set-Service -Name "CDPUserSvc_*" -StartupType "Automatic" *> $null
Set-Service -Name "COMSysApp" -StartupType "Manual" *> $null
Set-Service -Name "CaptureService_*" -StartupType "Manual" *> $null
Set-Service -Name "CertPropSvc" -StartupType "Manual" *> $null
Set-Service -Name "ClipSVC" -StartupType "Manual" *> $null
Set-Service -Name "ConsentUxUserSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "CoreMessagingRegistrar" -StartupType "Automatic" *> $null
Set-Service -Name "CredentialEnrollmentManagerUserSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "CryptSvc" -StartupType "Automatic" *> $null
Set-Service -Name "CscService" -StartupType "Manual" *> $null
Set-Service -Name "DPS" -StartupType "Automatic" *> $null
Set-Service -Name "DcomLaunch" -StartupType "Automatic" *> $null
Set-Service -Name "DevQueryBroker" -StartupType "Manual" *> $null
Set-Service -Name "DeviceAssociationBrokerSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "DeviceAssociationService" -StartupType "Manual" *> $null
Set-Service -Name "DeviceInstall" -StartupType "Manual" *> $null
Set-Service -Name "DevicePickerUserSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "DevicesFlowUserSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "Dhcp" -StartupType "Automatic" *> $null
Set-Service -Name "DiagTrack" -StartupType "Disabled" *> $null
Set-Service -Name "DialogBlockingService" -StartupType "Disabled" *> $null
Set-Service -Name "DispBrokerDesktopSvc" -StartupType "Automatic" *> $null
Set-Service -Name "DisplayEnhancementService" -StartupType "Manual" *> $null
Set-Service -Name "DmEnrollmentSvc" -StartupType "Manual" *> $null
Set-Service -Name "Dnscache" -StartupType "Automatic" *> $null
Set-Service -Name "DoSvc" -StartupType "AutomaticDelayedStart" *> $null
Set-Service -Name "DsSvc" -StartupType "Manual" *> $null
Set-Service -Name "DsmSvc" -StartupType "Manual" *> $null
Set-Service -Name "DusmSvc" -StartupType "Automatic" *> $null
Set-Service -Name "EFS" -StartupType "Manual" *> $null
Set-Service -Name "EapHost" -StartupType "Manual" *> $null
Set-Service -Name "EntAppSvc" -StartupType "Manual" *> $null
Set-Service -Name "EventLog" -StartupType "Automatic" *> $null
Set-Service -Name "EventSystem" -StartupType "Automatic" *> $null
Set-Service -Name "FDResPub" -StartupType "Manual" *> $null
Set-Service -Name "FontCache" -StartupType "Automatic" *> $null
Set-Service -Name "FrameServer" -StartupType "Manual" *> $null
Set-Service -Name "FrameServerMonitor" -StartupType "Manual" *> $null
Set-Service -Name "GraphicsPerfSvc" -StartupType "Manual" *> $null
Set-Service -Name "HvHost" -StartupType "Manual" *> $null
Set-Service -Name "IKEEXT" -StartupType "Manual" *> $null
Set-Service -Name "InstallService" -StartupType "Manual" *> $null
Set-Service -Name "InventorySvc" -StartupType "Manual" *> $null
Set-Service -Name "IpxlatCfgSvc" -StartupType "Manual" *> $null
Set-Service -Name "KeyIso" -StartupType "Automatic" *> $null
Set-Service -Name "KtmRm" -StartupType "Manual" *> $null
Set-Service -Name "LSM" -StartupType "Automatic" *> $null
Set-Service -Name "LanmanServer" -StartupType "Automatic" *> $null
Set-Service -Name "LanmanWorkstation" -StartupType "Automatic" *> $null
Set-Service -Name "LicenseManager" -StartupType "Manual" *> $null
Set-Service -Name "LxpSvc" -StartupType "Manual" *> $null
Set-Service -Name "MSDTC" -StartupType "Manual" *> $null
Set-Service -Name "MSiSCSI" -StartupType "Manual" *> $null
Set-Service -Name "MapsBroker" -StartupType "AutomaticDelayedStart" *> $null
Set-Service -Name "McpManagementService" -StartupType "Manual" *> $null
Set-Service -Name "MessagingService_*" -StartupType "Manual" *> $null
Set-Service -Name "MicrosoftEdgeElevationService" -StartupType "Manual" *> $null
Set-Service -Name "MpsSvc" -StartupType "Automatic" *> $null
Set-Service -Name "MsKeyboardFilter" -StartupType "Manual" *> $null
Set-Service -Name "NPSMSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "NaturalAuthentication" -StartupType "Manual" *> $null
Set-Service -Name "NcaSvc" -StartupType "Manual" *> $null
Set-Service -Name "NcbService" -StartupType "Manual" *> $null
Set-Service -Name "NcdAutoSetup" -StartupType "Manual" *> $null
Set-Service -Name "NetSetupSvc" -StartupType "Manual" *> $null
Set-Service -Name "Netlogon" -StartupType "Automatic" *> $null
Set-Service -Name "Netman" -StartupType "Manual" *> $null
Set-Service -Name "NgcCtnrSvc" -StartupType "Manual" *> $null
Set-Service -Name "NgcSvc" -StartupType "Manual" *> $null
Set-Service -Name "NlaSvc" -StartupType "Manual" *> $null
Set-Service -Name "P9RdrService_*" -StartupType "Manual" *> $null
Set-Service -Name "PcaSvc" -StartupType "Manual" *> $null
Set-Service -Name "PeerDistSvc" -StartupType "Manual" *> $null
Set-Service -Name "PenService_*" -StartupType "Manual" *> $null
Set-Service -Name "PerfHost" -StartupType "Manual" *> $null
Set-Service -Name "PhoneSvc" -StartupType "Manual" *> $null
Set-Service -Name "PimIndexMaintenanceSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "PlugPlay" -StartupType "Manual" *> $null
Set-Service -Name "PolicyAgent" -StartupType "Manual" *> $null
Set-Service -Name "Power" -StartupType "Automatic" *> $null
Set-Service -Name "PrintNotify" -StartupType "Manual" *> $null
Set-Service -Name "PrintWorkflowUserSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "ProfSvc" -StartupType "Automatic" *> $null
Set-Service -Name "PushToInstall" -StartupType "Manual" *> $null
Set-Service -Name "QWAVE" -StartupType "Manual" *> $null
Set-Service -Name "RasAuto" -StartupType "Manual" *> $null
Set-Service -Name "RasMan" -StartupType "Manual" *> $null
Set-Service -Name "RemoteAccess" -StartupType "Disabled" *> $null
Set-Service -Name "RemoteRegistry" -StartupType "Disabled" *> $null
Set-Service -Name "RetailDemo" -StartupType "Manual" *> $null
Set-Service -Name "RmSvc" -StartupType "Manual" *> $null
Set-Service -Name "RpcEptMapper" -StartupType "Automatic" *> $null
Set-Service -Name "RpcLocator" -StartupType "Manual" *> $null
Set-Service -Name "RpcSs" -StartupType "Automatic" *> $null
Set-Service -Name "SCPolicySvc" -StartupType "Manual" *> $null
Set-Service -Name "SCardSvr" -StartupType "Manual" *> $null
Set-Service -Name "SDRSVC" -StartupType "Manual" *> $null
Set-Service -Name "SEMgrSvc" -StartupType "Manual" *> $null
Set-Service -Name "SENS" -StartupType "Automatic" *> $null
Set-Service -Name "SNMPTRAP" -StartupType "Manual" *> $null
Set-Service -Name "SNMPTrap" -StartupType "Manual" *> $null
Set-Service -Name "SSDPSRV" -StartupType "Manual" *> $null
Set-Service -Name "SamSs" -StartupType "Automatic" *> $null
Set-Service -Name "ScDeviceEnum" -StartupType "Manual" *> $null
Set-Service -Name "Schedule" -StartupType "Automatic" *> $null
Set-Service -Name "SecurityHealthService" -StartupType "Manual" *> $null
Set-Service -Name "Sense" -StartupType "Manual" *> $null
Set-Service -Name "SensorDataService" -StartupType "Manual" *> $null
Set-Service -Name "SensorService" -StartupType "Manual" *> $null
Set-Service -Name "SensrSvc" -StartupType "Manual" *> $null
Set-Service -Name "SessionEnv" -StartupType "Manual" *> $null
Set-Service -Name "SgrmBroker" -StartupType "Automatic" *> $null
Set-Service -Name "SharedAccess" -StartupType "Manual" *> $null
Set-Service -Name "ShellHWDetection" -StartupType "Automatic" *> $null
Set-Service -Name "SmsRouter" -StartupType "Manual" *> $null
Set-Service -Name "Spooler" -StartupType "Automatic" *> $null
Set-Service -Name "SstpSvc" -StartupType "Manual" *> $null
Set-Service -Name "StateRepository" -StartupType "Manual" *> $null
Set-Service -Name "StiSvc" -StartupType "Manual" *> $null
Set-Service -Name "StorSvc" -StartupType "Manual" *> $null
Set-Service -Name "SysMain" -StartupType "Automatic" *> $null
Set-Service -Name "SystemEventsBroker" -StartupType "Automatic" *> $null
Set-Service -Name "TapiSrv" -StartupType "Manual" *> $null
Set-Service -Name "TermService" -StartupType "Automatic" *> $null
Set-Service -Name "TextInputManagementService" -StartupType "Manual" *> $null
Set-Service -Name "Themes" -StartupType "Automatic" *> $null
Set-Service -Name "TieringEngineService" -StartupType "Manual" *> $null
Set-Service -Name "TimeBrokerSvc" -StartupType "Manual" *> $null
Set-Service -Name "TokenBroker" -StartupType "Manual" *> $null
Set-Service -Name "TrkWks" -StartupType "Automatic" *> $null
Set-Service -Name "TroubleshootingSvc" -StartupType "Manual" *> $null
Set-Service -Name "TrustedInstaller" -StartupType "Manual" *> $null
Set-Service -Name "UdkUserSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "UevAgentService" -StartupType "Disabled" *> $null
Set-Service -Name "UmRdpService" -StartupType "Manual" *> $null
Set-Service -Name "UnistoreSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "UserDataSvc_*" -StartupType "Manual" *> $null
Set-Service -Name "UserManager" -StartupType "Automatic" *> $null
Set-Service -Name "UsoSvc" -StartupType "Manual" *> $null
Set-Service -Name "VSS" -StartupType "Manual" *> $null
Set-Service -Name "VaultSvc" -StartupType "Automatic" *> $null
Set-Service -Name "W32Time" -StartupType "Manual" *> $null
Set-Service -Name "WEPHOSTSVC" -StartupType "Manual" *> $null
Set-Service -Name "WFDSConMgrSvc" -StartupType "Manual" *> $null
Set-Service -Name "WManSvc" -StartupType "Manual" *> $null
Set-Service -Name "WPDBusEnum" -StartupType "Manual" *> $null
Set-Service -Name "WSearch" -StartupType "AutomaticDelayedStart" *> $null
Set-Service -Name "WaaSMedicSvc" -StartupType "Manual" *> $null
Set-Service -Name "WalletService" -StartupType "Manual" *> $null
Set-Service -Name "WarpJITSvc" -StartupType "Manual" *> $null
Set-Service -Name "WbioSrvc" -StartupType "Manual" *> $null
Set-Service -Name "Wcmsvc" -StartupType "Automatic" *> $null
Set-Service -Name "WdNisSvc" -StartupType "Manual" *> $null
Set-Service -Name "WdiServiceHost" -StartupType "Manual" *> $null
Set-Service -Name "WdiSystemHost" -StartupType "Manual" *> $null
Set-Service -Name "WebClient" -StartupType "Manual" *> $null
Set-Service -Name "Wecsvc" -StartupType "Manual" *> $null
Set-Service -Name "WerSvc" -StartupType "Manual" *> $null
Set-Service -Name "WiaRpc" -StartupType "Manual" *> $null
Set-Service -Name "WinDefend" -StartupType "Automatic" *> $null
Set-Service -Name "WinHttpAutoProxySvc" -StartupType "Manual" *> $null
Set-Service -Name "WinRM" -StartupType "Manual" *> $null
Set-Service -Name "Winmgmt" -StartupType "Automatic" *> $null
Set-Service -Name "WlanSvc" -StartupType "Automatic" *> $null
Set-Service -Name "WpcMonSvc" -StartupType "Manual" *> $null
Set-Service -Name "WpnService" -StartupType "Manual" *> $null
Set-Service -Name "WpnUserService_*" -StartupType "Automatic" *> $null
Set-Service -Name "XblAuthManager" -StartupType "Manual" *> $null
Set-Service -Name "XblGameSave" -StartupType "Manual" *> $null
Set-Service -Name "XboxGipSvc" -StartupType "Manual" *> $null
Set-Service -Name "XboxNetApiSvc" -StartupType "Manual" *> $null
Set-Service -Name "autotimesvc" -StartupType "Manual" *> $null
Set-Service -Name "bthserv" -StartupType "Manual" *> $null
Set-Service -Name "camsvc" -StartupType "Manual" *> $null
Set-Service -Name "cbdhsvc_*" -StartupType "Manual" *> $null
Set-Service -Name "cloudidsvc" -StartupType "Manual" *> $null
Set-Service -Name "dcsvc" -StartupType "Manual" *> $null
Set-Service -Name "defragsvc" -StartupType "Manual" *> $null
Set-Service -Name "diagsvc" -StartupType "Manual" *> $null
Set-Service -Name "dmwappushservice" -StartupType "Manual" *> $null
Set-Service -Name "dot3svc" -StartupType "Manual" *> $null
Set-Service -Name "edgeupdate" -StartupType "Manual" *> $null
Set-Service -Name "edgeupdatem" -StartupType "Manual" *> $null
Set-Service -Name "embeddedmode" -StartupType "Manual" *> $null
Set-Service -Name "fdPHost" -StartupType "Manual" *> $null
Set-Service -Name "fhsvc" -StartupType "Manual" *> $null
Set-Service -Name "gpsvc" -StartupType "Automatic" *> $null
Set-Service -Name "hidserv" -StartupType "Manual" *> $null
Set-Service -Name "icssvc" -StartupType "Manual" *> $null
Set-Service -Name "iphlpsvc" -StartupType "Automatic" *> $null
Set-Service -Name "lfsvc" -StartupType "Manual" *> $null
Set-Service -Name "lltdsvc" -StartupType "Manual" *> $null
Set-Service -Name "lmhosts" -StartupType "Manual" *> $null
Set-Service -Name "mpssvc" -StartupType "Automatic" *> $null
Set-Service -Name "msiserver" -StartupType "Manual" *> $null
Set-Service -Name "netprofm" -StartupType "Manual" *> $null
Set-Service -Name "nsi" -StartupType "Automatic" *> $null
Set-Service -Name "perceptionsimulation" -StartupType "Manual" *> $null
Set-Service -Name "pla" -StartupType "Manual" *> $null
Set-Service -Name "seclogon" -StartupType "Manual" *> $null
Set-Service -Name "shpamsvc" -StartupType "Disabled" *> $null
Set-Service -Name "smphost" -StartupType "Manual" *> $null
Set-Service -Name "sppsvc" -StartupType "AutomaticDelayedStart" *> $null
Set-Service -Name "svsvc" -StartupType "Manual" *> $null
Set-Service -Name "swprv" -StartupType "Manual" *> $null
Set-Service -Name "tzautoupdate" -StartupType "Disabled" *> $null
Set-Service -Name "upnphost" -StartupType "Manual" *> $null
Set-Service -Name "vds" -StartupType "Manual" *> $null
Set-Service -Name "vmicguestinterface" -StartupType "Manual" *> $null
Set-Service -Name "vmicheartbeat" -StartupType "Manual" *> $null
Set-Service -Name "vmickvpexchange" -StartupType "Manual" *> $null
Set-Service -Name "vmicrdv" -StartupType "Manual" *> $null
Set-Service -Name "vmicshutdown" -StartupType "Manual" *> $null
Set-Service -Name "vmictimesync" -StartupType "Manual" *> $null
Set-Service -Name "vmicvmsession" -StartupType "Manual" *> $null
Set-Service -Name "vmicvss" -StartupType "Manual" *> $null
Set-Service -Name "wbengine" -StartupType "Manual" *> $null
Set-Service -Name "wcncsvc" -StartupType "Manual" *> $null
Set-Service -Name "webthreatdefsvc" -StartupType "Manual" *> $null
Set-Service -Name "webthreatdefusersvc_*" -StartupType "Automatic" *> $null
Set-Service -Name "wercplsupport" -StartupType "Manual" *> $null
Set-Service -Name "wisvc" -StartupType "Manual" *> $null
Set-Service -Name "wlidsvc" -StartupType "Manual" *> $null
Set-Service -Name "wlpasvc" -StartupType "Manual" *> $null
Set-Service -Name "wmiApSrv" -StartupType "Manual" *> $null
Set-Service -Name "wscsvc" -StartupType "AutomaticDelayedStart" *> $null
Set-Service -Name "wuauserv" -StartupType "Manual" *> $null
