$store='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore'; $appx=Get-AppxPackage -AllUsers -Name "Microsoft.SecHealthUI"; $extraSids = if (Test-Path $store) { Get-ChildItem $store -ea 0 | ForEach-Object { $_.PSChildName } | Where-Object { $_ -like 'S-1-5-21*' } } else { @() }; foreach ($sid in @('S-1-5-18') + $extraSids) { New-Item "$store\EndOfLife\$sid\$($appx.PackageFullName)" -Fo | Out-Null }; New-Item "$store\Deprovisioned\$($appx.PackageFamilyName)" -Fo | Out-Null; Remove-AppxPackage -Package $appx.PackageFullName; Install-PackageProvider -Name NuGet -Force | Out-Null; Install-Module -Name NtObjectManager -Force -Confirm:$false; Set-ExecutionPolicy -ExecutionPolicy Bypass -Force; iwr 'https://github.com/ionuttbara/windows-defender-remover/raw/main/Remove_Defender/RemoveDefender.reg' -OutFile "$env:TEMP\RemoveDefender.reg"; iwr 'https://github.com/ionuttbara/windows-defender-remover/raw/main/Remove_SecurityComp/Remove_SecurityComp.reg' -OutFile "$env:TEMP\Remove_SecurityComp.reg"; Start-Service TrustedInstaller; New-Win32Process -Config (New-Win32ProcessConfig -CommandLine "cmd.exe /c reg import `"$env:TEMP\RemoveDefender.reg`" & reg import `"$env:TEMP\Remove_SecurityComp.reg`"" -CreationFlags NewConsole -ParentProcess (Get-NtProcess -ServiceName TrustedInstaller)) | Out-Null
$store = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore'; $appx = Get-AppxPackage -AllUsers -Name Microsoft.SecHealthUI; $sids = @('S-1-5-18')

$sids += Get-ChildItem $store -ea 0 | % { $_.PSChildName } | ? { $_.StartsWith('S-1-5-21') }
New-Item "$store\Deprovisioned\$($appx.PackageFamilyName)" -Force | Out-Null
foreach ($sid in $sids) { New-Item "$store\EndOfLife\$sid\$($appx.PackageFullName)" -Force | Out-Null }; $appx | Remove-AppxPackage

Install-PackageProvider -Name NuGet -Force | Out-Null; Install-Module -Name NtObjectManager -Force -Confirm:$false; Set-ExecutionPolicy -ExecutionPolicy Bypass -Force
iwr 'https://github.com/ionuttbara/windows-defender-remover/raw/main/Remove_Defender/RemoveDefender.reg' -OutFile "$env:TEMP\RemoveDefender.reg"
iwr 'https://github.com/ionuttbara/windows-defender-remover/raw/main/Remove_SecurityComp/Remove_SecurityComp.reg' -OutFile "$env:TEMP\Remove_SecurityComp.reg"
Start-Service TrustedInstaller; New-Win32Process -Config (New-Win32ProcessConfig -CommandLine "cmd.exe /c reg import `"$env:TEMP\RemoveDefender.reg`" & reg import `"$env:TEMP\Remove_SecurityComp.reg`"" -CreationFlags NewConsole -ParentProcess (Get-NtProcess -ServiceName TrustedInstaller)) | Out-Null
