Disable-WindowsOptionalFeature -O -F Microsoft-RemoteDesktopConnection
& $env:SystemRoot\System32\OneDriveSetup.exe /uninstall

$Packages = @(
    "Microsoft.WindowsCalculator"
    "Microsoft.WindowsCamera"
    "Microsoft.WindowsAlarms"
    "Microsoft.WindowsFeedbackHub"
    "Microsoft.ZuneMusic"
    "Microsoft.MicrosoftOfficeHub"
    "Microsoft.BingSearch"
    "Microsoft.BingWeather"
    "Microsoft.BingNews"
    "Clipchamp.Clipchamp"
    "MSTeams"
    "Microsoft.Todos"
    "Microsoft.OutlookForWindows"
    "Microsoft.Paint"
    "Microsoft.Windows.Photos"
    "MicrosoftCorporationII.QuickAssist"
    "Microsoft.ScreenSketch"
    "Microsoft.MicrosoftSolitaireCollection"
    "Microsoft.WindowsSoundRecorder"
    "Microsoft.StartExperiencesApp"
    "Microsoft.MicrosoftStickyNotes"
    "Microsoft.WindowsTerminal"
    "Microsoft.WebMediaExtensions"
    "Microsoft.GamingApp"
    "Microsoft.PowerAutomateDesktop"
    "Microsoft.Xbox.TCUI"
    "Microsoft.Windows.DevHome"
    "Microsoft.XboxGamingOverlay"
    "Microsoft.GetHelp"
    "Microsoft.WindowsStore"
    "MicrosoftWindows.CrossDevice"
    "Microsoft.YourPhone"
    "Microsoft.Application*"
)

foreach ($Package in $Packages) { Get-AppxPackage $Package | Remove-AppPackage }
